### ISSUE TITLE
Occupancy points for Matterport dataset

### ISSUE THREAD

**Issue by shamitlal** [autonomousvision/convolutional_occupancy_networks#10]
Hi,
I am interested in running the code on matterport data. But I can't find the points.npy file similar to shapenet dataset which has points sampled randomly inside the bounds. Can you please help me with this?

Thanks
Shamit

**Comment by pengsongyou** [comment]
Hi Shamit,

Thanks for your interest in our work. For Matterport3D experiment, we don't train at all on Matterport3D dataset, but only trained on the small crops of our synthetic room dataset. Therefore, during inference, we only require pointcloud.npz file as the input, which are the surface points.
