### ISSUE TITLE
Question about data sampling strategy in synthetic indoor scene dataset

### ISSUE THREAD

**Issue by Steve-Tod** [autonomousvision/convolutional_occupancy_networks#11]
Hi there, thank you for making the code public!

I have a question about data sampling strategy in synthetic indoor scene dataset.

After placing the object in the room, do you randomly sample points and query their ground truth occupancy in the whole scene? If so, wouldn't the occupancy data severely biased toward empty (since most space inside the room should be empty)?

Another question is that: how many point-occupancy pairs do you sample for one batch?

I'm not able to clearly locate these details in the code, so I raise the issue to ask. Thank you for your time!

**Comment by pengsongyou** [comment]
Hi @Steve-Tod, 

Thanks for your interest in our project.

> Hi there, thank you for making the code public!
> 
> I have a question about data sampling strategy in synthetic indoor scene dataset.
> 
> After placing the object in the room, do you randomly sample points and query their ground truth occupancy in the whole scene? If so, wouldn't the occupancy data severely biased toward empty (since most space inside the room should be empty)?
> 
Yes, we uniformly sample points inside the uni cube, as shown [here](https://github.com/autonomousvision/convolutional_occupancy_networks/blob/10878b80834a325ca643c98f54b41963ca0fdd7a/scripts/dataset_synthetic_room/build_dataset.py#L257-L300). Indeed, a large number of points are empty, but we did not really spot performance drop for our method. However, indeed many other methods sample more points near surfaces, and probably leads to faster convergence and maybe slightly better performance, but we did not do that in our project.

> Another question is that: how many point-occupancy pairs do you sample for one batch?

Normally we sample 2048 in one batch for every instance. You can find it [here](https://github.com/autonomousvision/convolutional_occupancy_networks/blob/10878b80834a325ca643c98f54b41963ca0fdd7a/configs/pointcloud/room_3plane.yaml#L8). 
> 
> I'm not able to clearly locate these details in the code, so I raise the issue to ask. Thank you for your time!

Hope my answer helps.

**Comment by Steve-Tod** [comment]
Thank you for your quick response! One more question, how many point-occupancy pairs do you sample per scene during the data generation phase? Is that 100000 * 10 in [here](https://github.com/autonomousvision/convolutional_occupancy_networks/blob/10878b80834a325ca643c98f54b41963ca0fdd7a/scripts/dataset_synthetic_room/build_dataset.py#L47)?

**Comment by pengsongyou** [comment]
> Thank you for your quick response! One more question, how many point-occupancy pairs do you sample per scene during the data generation phase? Is that 100000 * 10 in [here](https://github.com/autonomousvision/convolutional_occupancy_networks/blob/10878b80834a325ca643c98f54b41963ca0fdd7a/scripts/dataset_synthetic_room/build_dataset.py#L47)?

Yes, exactly. If you download the dataset, you will find it.

**Comment by Steve-Tod** [comment]
Thank you!

**Comment by grau4** [comment]
Hi there!

I'm trying to evaluate your method in my own application, for which I have voxelized room scenes just like the ones in the "synthetic_room_dataset". From "configs/pointcloud_crop/room_grid64.yam" and your paper I understand that the task can be done with the PatchLocalDecoder network. In the comment above, @pengsongyou mentioned that the query points p for this case are sampled within the entire scene, scaled to the unit cube, just like the scene itself. However, unlike the LocalDecoder for single shapes, forward application of the PatchLocalDecoder network requires points 'p' and 'p_n', but I cant spot the difference between these two in the repo. I'm overall failing to see how this decoder works crop-wise.

Best.

**Comment by pengsongyou** [comment]
> Hi there!
> 
> I'm trying to evaluate your method in my own application, for which I have voxelized room scenes just like the ones in the "synthetic_room_dataset". From "configs/pointcloud_crop/room_grid64.yam" and your paper I understand that the task can be done with the PatchLocalDecoder network. In the comment above, @pengsongyou mentioned that the query points p for this case are sampled within the entire scene, scaled to the unit cube, just like the scene itself. However, unlike the LocalDecoder for single shapes, forward application of the PatchLocalDecoder network requires points 'p' and 'p_n', but I cant spot the difference between these two in the repo. I'm overall failing to see how this decoder works crop-wise.
> 
> Best.

Hi @grau4 , let's say we sample 10000 points from one entire scene, but we only crop some small parts from there. We still keep all points, but only encode those points falling into the crop. In the decoder, we can sample random points only within the crop and predict their occupancies. That is the basic idea of the crop-wise method. In practice we actually consider a bigger crop in the encoder part than the crop while decoding (in order to deal with the boundary among different crops). More technical details can be found in Section 6 in the [supplementary](http://www.cvlibs.net/publications/Peng2020ECCV_supplementary.pdf). 

Hope this answers your question.

**Comment by grau4** [comment]
Ok. So, if 'PatchLocalDecoder' only samples points within the crop then this means that: 1) 'p_n' are the points locally sampled strictly within the crop, and 2) 'p' are those points sampled over the entire scene (the 10000 you mention) that fall within the crop. Did I get this right?

**Comment by pengsongyou** [comment]
> Ok. So, if 'PatchLocalDecoder' only samples points within the crop then this means that: 1) 'p_n' are the points locally sampled strictly within the crop, and 2) 'p' are those points sampled over the entire scene (the 10000 you mention) that fall within the crop. Did I get this right?

@grau4, no, we sample 10000 surface points from the entire room, and when we crop out some bounding box. 'p' are all 10000 points in the entire room. However, we set those points outside of the bounding box the same index, which is the same as resolution^3, as shown [here](https://github.com/autonomousvision/convolutional_occupancy_networks/blob/master/src/data/fields.py#L253)). During encoding, we only aggregate those points falling into the bounding box, and filter out those points outside (outliers). This is done [here](https://github.com/autonomousvision/convolutional_occupancy_networks/blob/master/src/encoder/pointnet.py#L255-L258).

Best,
Songyou
