### ISSUE TITLE
SPSR

### ISSUE THREAD

**Issue by XuyangBai** [autonomousvision/convolutional_occupancy_networks#14]
Hi @pengsongyou Thanks a lot for sharing this excellent work.  I wonder would you mind also share the code for Screened Poisson Surface Reconstruction? or did you use some open-source implementation?

Best,
Xuyang

**Comment by pengsongyou** [comment]
Hi @XuyangBai , thanks for your interest in our work. I am using the official implementation of SPSR. You can find it at [here](http://www.cs.jhu.edu/~misha/Code/PoissonRecon/Version13.72/#EXECUTABLES) and [here](https://github.com/mkazhdan/PoissonRecon).

Hope it helps.

Best,
Songyou

**Comment by XuyangBai** [comment]
Thanks a lot :)
