### ISSUE TITLE
How can occupany network be applied in real applications

### ISSUE THREAD

**Issue by wzic** [autonomousvision/convolutional_occupancy_networks#16]
Hi! It's nice to see your work on implicit representation of 3D shapes. May I have your idea on how the (convolutional) occupancy network can be used in real applications?

For example, if a robot wants to grab a chair in front of it with its arm, does it need to query all the points in between itself and the target item (the chair) so as to precisely determine the coordinates of the legs? In other words, how can the occupany network be used to calculate the distance?

Thank you.

**Comment by pengsongyou** [comment]
@wzic you might find [this paper](https://sites.google.com/view/rpl-giga2021) interested because they build on top of the architecture of ConvONet and apply to robot grasping.
