### ISSUE TITLE
Urban 3D reconstruction

### ISSUE THREAD

**Issue by abhishek31704** [autonomousvision/convolutional_occupancy_networks#18]
Hi, 

Is there a way to apply this approach on point clouds of urban scene and get 3D reconstruction?

**Comment by abhishek31704** [comment]
Hi,

I did run generate demo matterport to get the 3D of a 2 floor building interior. 

What I am looking for is to get a 3D building reconstruction of a few city building. 

Could you suggest where can I get a dataset for Urban scenes to generate a 3D model based on provided model.

**Comment by pengsongyou** [comment]
Hi,

Your task seems to focus on another application than ours (detailed reconstruction of interior reconstruction). Therefore, I do not really have an idea of how to generate the dataset for your specific task.
