### ISSUE TITLE
CUDA runtime error

### ISSUE THREAD

**Issue by abhishek31704** [autonomousvision/convolutional_occupancy_networks#19]
Hi, 

When I run the following script:
python generate.py configs/pointcloud_crop/demo_matterport.yaml

runtimeError: CUDA out of memory. Tried to allocate 376.00 MiB

I tried reducing the batch size from 2 to 1 but still not working. 

Any solution?

**Comment by pengsongyou** [comment]
Hi @abhishek31704 

I don't know what GPU you are using, but probably with a small memory? If so, you can consider decreasing the [query_vol_size](https://github.com/autonomousvision/convolutional_occupancy_networks/blob/master/configs/pointcloud_crop/demo_matterport.yaml#L14). This should solve your problem but it might be slower.

Best,
Songyou

**Comment by XiaoyanQian** [comment]
> query_vol_size

Hi， do you use one 3090? I have a similar error of "RuntimeError: CUDA error: an illegal memory access was encountered". it did not work for my case to decrease the query_vol_size
