### ISSUE TITLE
Discretization of the canonical plane

### ISSUE THREAD

**Issue by SrinjaySarkar** [autonomousvision/convolutional_occupancy_networks#2]
Hello Songyou, thank you for such a good paper and the code to go along with it.
The paper mentions the canonical plane is discretized as H*W during feature aggregation. What do H and W represent for point cloud inputs?

**Comment by pengsongyou** [comment]
Hi @SrinjaySarkar, I am not sure about your question. The plane is pre-defined as, for example, 64x64 for object-level reconstruction or 128x128 for scene-level reconstruction. Point clouds sampled from the surface are then projected to the plane, where we place the features from these points onto the plane according to their 2D coordinates. Therefore, H and W have nothing to do with the point cloud inputs.

**Comment by SrinjaySarkar** [comment]
Ahh I see, I misunderstood something in the paper. Thanks for the answer, it clears things up.
