### ISSUE TITLE
A few questions regarding your paper

### ISSUE THREAD

**Issue by Na-Z** [autonomousvision/convolutional_occupancy_networks#21]
Hi, thanks for sharing your great work!

I have a few questions:

1. You mentioned that "our method is independent of the input representation" in the paper. I am curious to know that if it is possible to use multi-view images as input in your framework. If the answer is yes, could you provide a hint how to implement that? 

2. If train your method in a real-world dataset and test on another real-world dataset, do you think it will still work? 

3. As mentioned in Sec. 6 of the supplementary material, you "randomly sample one point within the scene as the center of the crop". May I know how you balance the positive and negative samples (i.e., gt occupancy value  1 and 0) with random sampling?

Looking forward to your reply. Thanks.

**Comment by pengsongyou** [comment]
@Na-Z Thanks for your interest!


> Hi, thanks for sharing your great work!
> 
> I have a few questions:
> 
> 1. You mentioned that "our method is independent of the input representation" in the paper. I am curious to know that if it is possible to use multi-view images as input in your framework. If the answer is yes, could you provide a hint how to implement that?

We have not tackled the multi-view image inputs yet, but you can check out some recent papers like [this](https://arxiv.org/abs/2104.03851) and [this](https://arxiv.org/abs/2003.10432), where they show how to fuse multi-view images to a feature volume.

> 2. If train your method in a real-world dataset and test on another real-world dataset, do you think it will still work?

Sure, if you manage to generate such a real-world dataset for training, I think it should work and work better for real-world scenarios ;)

> 3. As mentioned in Sec. 6 of the supplementary material, you "randomly sample one point within the scene as the center of the crop". May I know how you balance the positive and negative samples (i.e., gt occupancy value  1 and 0) with random sampling?
> 

I did not check the balance between positive and negative samples, but I think we definitely have more negatives (free space).

> Looking forward to your reply. Thanks.

Hope I answer your questions.

Best,
Songyou

**Comment by Na-Z** [comment]
Hi Songyou, 

Thanks for your prompt reply.

May I know why not use ScanNet for training in your experiments? Any concern?

Best,
Na

**Comment by pengsongyou** [comment]
@Na-Z Because the ScanNet data is noisy and incomplete, plus we found that it generalizes already pretty well using the synthetic dataset training.

**Comment by Na-Z** [comment]
I see. Thanks.
