### ISSUE TITLE
How many epoches we need to train on synthetic room dataset?

### ISSUE THREAD

**Issue by ray8828** [autonomousvision/convolutional_occupancy_networks#22]
Hi, thanks for sharing your codes. I'm training 3planes and grid64 on the synthetic room dataset, How many epoches do you train to get the final numbers? Thanks!

**Comment by novauto-nju** [comment]
Have you found any information about **epoch**？My **epoch=110**, but the program didn't stop

**Comment by pengsongyou** [comment]
If you train with a batch size of 24, you need to train for 2500 epoch (~300K iterations).
