### ISSUE TITLE
GT mesh of synthetic dataset

### ISSUE THREAD

**Issue by JiahuiLei** [autonomousvision/convolutional_occupancy_networks#24]
Hi, Thanks for sharing this great work!

I would like to ask whether we could get access to the ground truth meshes of the synthetic indoor scene dataset. I might need to resample the field labels from your GT meshes. Thanks!

**Comment by pengsongyou** [comment]
Hi @JiahuiLei 

Thanks for your interest in our work! 

You can download the GT mesh from https://s3.eu-central-1.amazonaws.com/avg-projects/convolutional_occupancy_networks/data/room_watertight_mesh.zip. The zip file occupies roughly 90G of your disk.

Hope it helps.

Best, 
Songyou

**Comment by JiahuiLei** [comment]
Thanks! This really help me a lot!
