### ISSUE TITLE
Could not find a version that satisfies the requirement torch-scatter

### ISSUE THREAD

**Issue by QtEngineer** [autonomousvision/convolutional_occupancy_networks#26]

**Comment by QtEngineer** [comment]
cause cuda version is 112

**Comment by pengsongyou** [comment]
@QtEngineer 

I am not quite sure why this happened, maybe because torch-scatter has been updated. If you check https://github.com/rusty1s/pytorch_scatter, it seems that they only support cuda version up to 111.

Best,
Songyou
