### ISSUE TITLE
Bug in split list generation

### ISSUE THREAD

**Issue by twcostain** [autonomousvision/convolutional_occupancy_networks#27]
https://github.com/autonomousvision/convolutional_occupancy_networks/blob/f44d413f8d455657a44c24d06163934c69141a09/scripts/dataset_synthetic_room/build_dataset.py#L433

Because the counter is incremented before the first line is written to the string the split lists never contain scene 0, they start at 1.

**Comment by pengsongyou** [comment]
Hi @twcostain ,

Thanks for pointing it out, it is indeed the case, so you might want to remove scene 0 from the `train.lst` yourself :)

Best,
Songyou

**Comment by twcostain** [comment]
I've fixed it myself locally, just thought that you might want to know incase you ever update the repo :)
