### ISSUE TITLE
No noise in input point clouds?

### ISSUE THREAD

**Issue by raphaelsulzer** [autonomousvision/convolutional_occupancy_networks#30]
Hi,

thank you very much for making this great work available here.

I was experimenting with retraining your network for which I downloaded the preprocessed ShapeNet and synthetic room dataset.
You state in the paper that you "sample 3000 points from the mesh and apply Gaussian noise with zero mean and standard deviation 0.05" to generate noisy input point clouds. (I understand the reasoning in [this issue](https://github.com/autonomousvision/occupancy_networks/issues/18), and can see in the config files that it is actually 0.005.)

However, to me it seems like there is no added noise in neither the pointcloud.ply nor pointcloud.npz files in both the ShapeNet and synthetic room dataset. If I follow your approach correctly these files are generated with the [sample_mesh.ply](https://github.com/autonomousvision/occupancy_networks/blob/master/scripts/sample_mesh.py) script from the occupancy networks repository. In the [export_points](https://github.com/autonomousvision/occupancy_networks/blob/406f79468fb8b57b3e76816aaa73b1915c53ad22/scripts/sample_mesh.py#L168) function for generating occupancy samples noise is added, however not in the [export_pointcloud](https://github.com/autonomousvision/occupancy_networks/blob/406f79468fb8b57b3e76816aaa73b1915c53ad22/scripts/sample_mesh.py#L122) function, which is used as reconstruction input. Shouldn't this be the case, since you postulate to reconstruct meshes from noisy point clouds?

Kind regards

**Comment by pengsongyou** [comment]
Hi @raphaelsulzer ,

Thanks for your interest in our work! 

We don't add noise directly to our GT data. Instead, we add noises during the data loading process. Please refer to the code [here](https://github.com/autonomousvision/convolutional_occupancy_networks/blob/master/src/data/transforms.py#L5-L28) and [here](https://github.com/autonomousvision/convolutional_occupancy_networks/blob/f44d413f8d455657a44c24d06163934c69141a09/src/config.py#L164-L168).

Hope this resolves your question.

Best,
Songyou

**Comment by raphaelsulzer** [comment]
Yes, that makes it clear. Thank you!
