### ISSUE TITLE
Point cloud visulization

### ISSUE THREAD

**Issue by bluestyle97** [autonomousvision/convolutional_occupancy_networks#39]
Hi, I'm wondering how you visualize the point cloud as a set of small spheres as in the paper's figures? I found it is too hard to distinguish the points if I directly render the points. Could you please share the visualization tool or source code? Thanks a lot!

**Comment by pengsongyou** [comment]
Hi @bluestyle97, 

we were using an internal codebase to render point clouds with blender, so unfortunately we cannot share it. Nevertheless, I think there are some great public tools for your purpose. For example, [mitsuba-visualize](https://github.com/chrdiller/mitsuba-visualize) is a great tool to render meshes and point clouds and I personally really like it (I use it to generate the [fly-through video](https://github.com/autonomousvision/convolutional_occupancy_networks/blob/master/media/teaser_matterport.gif) for ConvONet), you can check it out.

Best,
Songyou

**Comment by bluestyle97** [comment]
I see, thank you very much!

Best Regards,
Jiale Xu
-------------------------------
***@***.***
