### ISSUE TITLE
coordinate2index function definition

### ISSUE THREAD

**Issue by Sj29** [autonomousvision/convolutional_occupancy_networks#4]
Hello @pengsongyou  thank you so much for the code, could you provide some explanation for the coordinate2index, It is my first time working with point clouds and I am little confused with that function.
Thanks.

**Comment by pengsongyou** [comment]
Hi @Sj29, thanks for your interest in our work.

In short, the coordinate2index function is used to convert point coordinates to the indices of the plane/volume with pre-defined resolution. The indices are later used by scatter_mean, which assigns point features to the defined plane/volume. Please check [here](https://github.com/autonomousvision/convolutional_occupancy_networks/blob/23337ae2a93d33e5f5a9ca107333bc301e5e74d6/src/encoder/pointnet.py#L69-L98).

Now I provide you with detailed comments for each line. Hope that helps you to understand better now.

```python
    # change value range from [0, 1] to plane/volume resolution, then convert float to integer
    x = (x * reso).long()
    if coord_type == '2d': # plane
        # calculate indices on the plane with defined resolution `reso`
        index = x[:, :, 0] + reso * x[:, :, 1]
    elif coord_type == '3d': # grid
        # calculate indices on the volume with defined resolution `reso`
        index = x[:, :, 0] + reso * (x[:, :, 1] + reso * x[:, :, 2])
    # add one more dimension to meet scatter_mean requirement
    index = index[:, None, :]
    return index
```

**Comment by Sj29** [comment]
Thank you very much, @pengsongyou .
