### ISSUE TITLE
Is Chamfer-L1 the result of multiplying by 10?

### ISSUE THREAD

**Issue by bluestyle97** [autonomousvision/convolutional_occupancy_networks#40]
When I evaluate the generated ShapeNet meshes myself, I found that the chamfer-l1 I got was an order of magnitude smaller than the value reported in the paper (I got 0.0048 instead of 0.048, and I'm using the official evaluation script in this repo).  So I'm wondering if the chamfer-l1 metric reported in the paper is the result of multiplying the real value by 10?

**Comment by pengsongyou** [comment]
I just added a clarification into the [evaluation section](https://github.com/autonomousvision/convolutional_occupancy_networks#evaluation) in README, please check it out.

**Comment by bluestyle97** [comment]
Oh I'm sorry I did not notice that, thanks for your explanation!
