### ISSUE TITLE
Inference/Generate with a generic .ply file

### ISSUE THREAD

**Issue by DuncanZauss** [autonomousvision/convolutional_occupancy_networks#42]
Hi,
Thank you for making the code for this nice project publicly available.
If I have a point cloud stored in a generic .ply file, how can I process it in such a way that I can run inference with the model that was trained on matterport? So is there some "build_dataset.py" file that is not for a specific dataset, but can just be used for a normal .ply file?
Best,
Duncan

**Comment by pengsongyou** [comment]
You can have a look at the [demo data](https://github.com/autonomousvision/convolutional_occupancy_networks/blob/master/scripts/download_demo_data.sh) for the matterport3D scene, and need to transfer your .ply file to the corresponding .npz file first. Then you simply need to modify [this line](https://github.com/autonomousvision/convolutional_occupancy_networks/blob/master/configs/pointcloud_crop/demo_matterport.yaml#L5) of the config file.

Hope it helps.

**Comment by DuncanZauss** [comment]
Thank you for the reply. Just a quick follow up question: What is the normals.npy file within npz file used for? From what I understood from your paper, only the location of the points matters, but not their (surface) normal.

**Comment by pengsongyou** [comment]
@DuncanZauss We don't use the normals as inputs, but use it for evaluation only.
