### ISSUE TITLE
How can I call multiple GPUs during training

### ISSUE THREAD

**Issue by miaowang525** [autonomousvision/convolutional_occupancy_networks#43]
hello   Your work is great and i am very interested in your article, and I have some questions to ask you.
I have five GPUs, how to call multiple GPUs to run code during training @pengsongyou

**Comment by pengsongyou** [comment]
Hi @miaowang525 , I did not try to train with multiple GPUs for this project, but it should be straightforward with [DataParallel](https://pytorch.org/docs/stable/generated/torch.nn.DataParallel.html) in PyTorch (simply do `net = torch.nn.DataParallel(model, device_ids=[0, 1, 2]`), or [DistributedDataParallel](https://pytorch.org/tutorials/intermediate/ddp_tutorial.html#comparison-between-dataparallel-and-distributeddataparallel) (recommended by PyTorch, but required more modifications).

Hope it helps.

Best,
Songyou
