### ISSUE TITLE
Post-Processing

### ISSUE THREAD

**Issue by ceteke** [autonomousvision/convolutional_occupancy_networks#44]
Dear authors,

Thank you for this nice work and sharing the code with the community! I wonder if there are any post-processing steps done (e.g. smoothing the meshes) after the 3D reconstruction, which might not be mentioned in the paper.

Best regards

**Comment by pengsongyou** [comment]
Hi @ceteke 

Thanks for your interest. There is no post-processing operations after the marching cubes. We indeed had a `refine_mesh` function (copy from the original Occupancy Networks repo):

https://github.com/autonomousvision/convolutional_occupancy_networks/blob/f15b97da2c5995598537c8f832e52e95c0b09236/src/conv_onet/generation.py#L419-L423

But we always set the refine to false, e.g. check [this config](https://github.com/autonomousvision/convolutional_occupancy_networks/blob/master/configs/pointcloud/room_1plane.yaml#L51).

Best,
Songyou
