### ISSUE TITLE
Bug in generating walls for synthetic dataset?

### ISSUE THREAD

**Issue by ZhaoyangZh** [autonomousvision/convolutional_occupancy_networks#47]
https://github.com/autonomousvision/convolutional_occupancy_networks/blob/f15b97da2c5995598537c8f832e52e95c0b09236/scripts/dataset_synthetic_room/build_dataset.py#L352

I think it should be `if walls[3] == 1`. Is it a typo?

**Comment by m-niemeyer** [comment]
Yes, you are right, thanks for spotting this!

**Comment by pengsongyou** [comment]
@ZhaoyangZh Thanks for pointing it out! We have updated the code accordingly: https://github.com/autonomousvision/convolutional_occupancy_networks/commit/c30692534d5e02d53c1fa34bd2696bd629d12632

Best
Songyou

**Comment by ZhaoyangZh** [comment]
My pleasure.
