### ISSUE TITLE
Ground Truth Mesh of the Synthetic Indoor Scene

### ISSUE THREAD

**Issue by samcao416** [autonomousvision/convolutional_occupancy_networks#48]
Hi, I just tried training the synthetic indoor scene with datasets downloaded from the link. It worked well. I want to compare the generated mesh with the ground-truth mesh, however, what I can find is some point clouds that seem to be the ground truth. Therefore, could you please help me with the ground-truth mesh of the synthetic indoor scene? Thanks a lot.

**Comment by samcao416** [comment]
Besides, could you please release an example config file of the scan-net dataset? I would like to try training on the more realistic scenes.

**Comment by pengsongyou** [comment]
Hi @samcao416, you can download the GT synthetic room mesh from the link below. 
```
wget https://s3.eu-central-1.amazonaws.com/avg-projects/convolutional_occupancy_networks/data/room_watertight_mesh.zip
```

As for the ScanNet, we did not train on it at all but directly applied the model trained on synthetic rooms to it. You can simply process the data as we mentioned [here](https://github.com/autonomousvision/convolutional_occupancy_networks#scannet). Then you can use a [pretrained model](https://github.com/autonomousvision/convolutional_occupancy_networks/blob/master/configs/pointcloud/pretrained/room_grid64.yaml) to directly infer ScanNete.

Best
Songyou

**Comment by samcao416** [comment]
Got it. Thanks a lot!

> Hi @samcao416, you can download the GT synthetic room mesh from the link below.
> 
> ```
> wget https://s3.eu-central-1.amazonaws.com/avg-projects/convolutional_occupancy_networks/data/room_watertight_mesh.zip
> ```
> 
> As for the ScanNet, we did not train on it at all but directly applied the model trained on synthetic rooms to it. You can simply process the data as we mentioned [here](https://github.com/autonomousvision/convolutional_occupancy_networks#scannet). Then you can use a [pretrained model](https://github.com/autonomousvision/convolutional_occupancy_networks/blob/master/configs/pointcloud/pretrained/room_grid64.yaml) to directly infer ScanNet.
> 
> Best Songyou

Got it. Thanks a lot!
