### ISSUE TITLE
train on outdoor LiDAR pointcloud

### ISSUE THREAD

**Issue by LongruiDong** [autonomousvision/convolutional_occupancy_networks#49]
Hi~

If I want to train a model on outdoor data like KITTI, which provide 64 line Velodyne LiDAR point cloud.

do you know how can I generate groundtruth occupancy values for a point cloud ?

**Comment by pengsongyou** [comment]
Please download some data that we provided, e.g. [synthetic indoor dataset](https://github.com/autonomousvision/convolutional_occupancy_networks#synthetic-indoor-scene-dataset), and check how we structure the data in each numpy array file.
