### ISSUE TITLE
error: command 'gcc' failed with exit status 1

### ISSUE THREAD

**Issue by Airobin329** [autonomousvision/convolutional_occupancy_networks#5]
gcc: error: /home/deploy/tmp/pycharm_project_794/convolutional_occupancy_networks/build/temp.linux-x86_64-3.7/src/utils/libkdtree/pykdtree/kdtree.o: No such file or directory
gcc: error: /home/deploy/tmp/pycharm_project_794/convolutional_occupancy_networks/build/temp.linux-x86_64-3.7/src/utils/libkdtree/pykdtree/_kdtree_core.o: No such file or directory

**Comment by pengsongyou** [comment]
Can you elaborate on your question?

**Comment by Airobin329** [comment]
I'm at set up.py When reporting this error. I've been looking for a long time. Go back to the occupancy_ Networks try that set up.py The same error. But I tried to install occnet successfully before. Now it's stuck in this place.

**Comment by Airobin329** [comment]
Could I copy the files“kdtree.o” “_kdtree_core.o”created in occnet and use them directly ?

**Comment by Airobin329** [comment]
I think it may be a matter of the environment?

**Comment by Airobin329** [comment]
it is OK！！！I changed my torch：
python                    3.6.7
torch                     1.5.0                  
torch-scatter             2.0.5                 
torchvision               0.2.1

**Comment by Airobin329** [comment]
sorry,I can not download the checkpoints from "model_file: https://s3.eu-central-1.amazonaws.com/avg-projects/convolutional_occupancy_networks/models/pointcloud_crop/room_grid64.pt".could you check it ?
