### ISSUE TITLE
Finetune for pretrained model

### ISSUE THREAD

**Issue by jeffsonyu** [autonomousvision/convolutional_occupancy_networks#53]
Hi! I'm currently using your pretrained model "room_grid64.gt". If I want to finetune it with a new dataset with pointcloud input, how should I set the config files? Thx!

**Comment by pengsongyou** [comment]
Please check and modify [this file](https://github.com/autonomousvision/convolutional_occupancy_networks/blob/master/configs/pointcloud_crop/room_grid64.yaml) accordingly.
