### ISSUE TITLE
How can I generate mesh with my own point cloud data

### ISSUE THREAD

**Issue by zhao-you-fei** [autonomousvision/convolutional_occupancy_networks#54]
@nynyg @pengsongyou @haofeixu 
How can I generate mesh with my own point cloud data, and what are the other input data?
Looking forward to your reply!

**Comment by pengsongyou** [comment]
> @nynyg @pengsongyou @haofeixu How can I generate mesh with my own point cloud data, and what are the other input data? Looking forward to your reply!

Hi @zhao-you-fei sorry for the delay. If you want to reconstruct from your own point cloud, please check how we organize our data in the provided demo data. You can download the data by `bash scripts/download_demo_data.sh`, and read different data fields in numpy array.

**Comment by pengsongyou** [comment]
> It could be very helpful if the pipeline of preparation of the training dataset could be supplied.

@Barnonewdm for shapenet data, ONet provided how they prepare the training set [here](https://github.com/autonomousvision/occupancy_networks#building-the-dataset). 

As for the synthetic indoor dataset, you can find how we prepare in the last paragraph of [this](https://github.com/autonomousvision/occupancy_networks#building-the-dataset).

**Comment by Barnonewdm** [comment]
> > It could be very helpful if the pipeline of preparation of the training dataset could be supplied.
> 
> @Barnonewdm for shapenet data, ONet provided how they prepare the training set [here](https://github.com/autonomousvision/occupancy_networks#building-the-dataset).
> 
> As for the synthetic indoor dataset, you can find how we prepare in the last paragraph of [this](https://github.com/autonomousvision/occupancy_networks#building-the-dataset).

Thanks a lot! A quick question. Do we need to prepare mesh as the ground truth, or just points should be enough?

**Comment by pengsongyou** [comment]
@Barnonewdm Check the demo data, you do not need to have GT mesh. Points should be fine.

**Comment by Barnonewdm** [comment]
> @Barnonewdm Check the demo data, you do not need to have GT mesh. Points should be fine.

I mean for the training. Only points are needed for training the model?
