### ISSUE TITLE
How to transform a mesh to a occupancy mat?

### ISSUE THREAD

**Issue by slypanzer** [autonomousvision/convolutional_occupancy_networks#56]
hellow, pengsongyou.
Sorry to bother you, but I have a problem when understanding your work. I want to know how to make label for training. How to transform a mesh to a occupancy mat and how to make cross-entropy for a query points? Do trilinear interpolation in the occupancy  matrix?

**Comment by pengsongyou** [comment]
Hi @slypanzer, for the ShapeNet object we directly use the data generation pipeline in Occupancy Networks: https://github.com/autonomousvision/occupancy_networks#building-the-dataset
