### ISSUE TITLE
Custom Dataset

### ISSUE THREAD

**Issue by Hemantr05** [autonomousvision/convolutional_occupancy_networks#7]
I would like to know the format to train convolutional occupancy network for a custom dataset. I have the sparse point cloud for my custom dataset.

Would appreciate any help for the same.

**Comment by pengsongyou** [comment]
I think you can simply check the code in [field.py](https://github.com/autonomousvision/convolutional_occupancy_networks/blob/master/src/data/fields.py). Note that we need not just the sparse point cloud sampled from surfaces, but also the occupancy values for random query points in space. You can check the class PointsField and PointCloudField.
