### ISSUE TITLE
version of 'cuda' and 'gcc'

### ISSUE THREAD

**Issue by maoqingsunny** [autonomousvision/convolutional_occupancy_networks#8]
I have some problems when running the code, I hope you can provide the version of 'gcc' and 'cuda'.

**Comment by maoqingsunny** [comment]
I get this error when I  run the demo."RuntimeError: cuda runtime error (98) : invalid device function at /opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/THC/generic/THCTensorScatterGather.cu:71"

**Comment by pengsongyou** [comment]
I am not sure why this happened. May I know how you install the environment? Could you please send the log when typing "conda list" inside the environment?

**Comment by maoqingsunny** [comment]
![选区_002](https://user-images.githubusercontent.com/45910917/96112678-9c8abd00-0f15-11eb-8207-2eb9a602ffc7.png)
![选区_003](https://user-images.githubusercontent.com/45910917/96112686-a14f7100-0f15-11eb-9a59-008d7d954626.png)
![选区_004](https://user-images.githubusercontent.com/45910917/96112693-a3b1cb00-0f15-11eb-9eb6-ff076f6b3edd.png)

**Comment by pengsongyou** [comment]
Looks good, weird...Can you try to run the command below and let me know if this helps: 
```
pip install torch-scatter==latest+cu101 -f https://pytorch-geometric.com/whl/torch-1.4.0.html
```

**Comment by maoqingsunny** [comment]
It's ok, It may be a problem with the  version of torch-scatter. I install the  2.0.4,It works fine. Thanks very much.
